# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=2.1
group=com.mars.lavasand
java_version=17
deimos_version=2.1
# Common
mod_name=Lava Turns Sand into Glass
mod_author=Mars
mod_id=lavasand
license=MIT
homepage=https://www.curseforge.com/minecraft/mc-mods/lava-turns-sand-into-glass-fabric-forge
description=When Lava Touches Sand Blocks They Turn into Glass Blocks
minecraft_version=1.20.4
modmenu_version=9.0.0
minecraft_version_range=[1.20.3, 1.21)
# Fabric
fabric_version=0.97.2+1.20.4
fabric_loader_version=0.16.9
# Forge
forge_version=49.0.19
forge_loader_version_range=[49,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
